import React, { useEffect, useMemo, useState } from 'react'
import api from '../services/api'
import { Link } from 'react-router-dom'
import DramaCard, { DramaCardData } from '../components/DramaCard'

export default function CardsList() {
  const [cards, setCards] = useState<DramaCardData[]>([]); const [library, setLibrary] = useState<DramaCardData[]>([]); const [adding, setAdding] = useState<string | null>(null); const [notice, setNotice] = useState('')
  useEffect(() => { Promise.all([api.get('/cards'), api.get('/cards/library')]).then(([owned, catalogue]) => { setCards(owned.data.cards); setLibrary(catalogue.data.cards) }).catch(() => setNotice('Non riesco a caricare il mazzo. Riprova tra poco.')) }, [])
  const ownedSlugs = useMemo(() => new Set(cards.map((card) => card.librarySlug)), [cards])
  const isOwned = (card: DramaCardData) => card.catalogCardId ? cards.some((owned) => owned.catalogCardId === card.catalogCardId) : ownedSlugs.has(card.slug)
  const addToDeck = async (card: DramaCardData) => { const cardKey = card.catalogCardId || card.slug; if (!cardKey) return; setAdding(cardKey); setNotice(''); try { const response = await api.post(card.catalogCardId ? `/cards/library/custom/${card.catalogCardId}` : `/cards/library/${card.slug}`); if (!cards.some((owned) => owned.id === response.data.card.id)) setCards((current) => [response.data.card, ...current]); setNotice(response.data.alreadyAdded ? 'Questa carta era gia nel tuo mazzo.' : `${card.title} e stata aggiunta al tuo mazzo.`) } catch { setNotice('Non sono riuscito ad aggiungere la carta. Riprova.') } finally { setAdding(null) } }
  return <div><div className="page-heading"><div><p className="eyebrow">L arsenale del caos</p><h2>Carte Drama</h2></div><Link to="/cards/create" className="btn">+ Crea carta</Link></div><p className="page-lead">Crea una carta con immagine IA e descrizione uniche: entrera nel catalogo per tutti i giocatori.</p>{notice && <div className="deck-notice" role="status">{notice}</div>}<section className="deck-section"><div className="deck-section-head"><div><p className="eyebrow">Collezione personale</p><h3>Il tuo mazzo <span>{cards.length}</span></h3></div></div>{cards.length ? <div className="drama-card-grid owned-card-grid">{cards.map(card => <DramaCard key={card.id} card={card} />)}</div> : <div className="empty-state">Il tuo mazzo e vuoto: scegli una carta dal catalogo qui sotto.</div>}</section><section className="deck-section library-section"><div className="deck-section-head"><div><p className="eyebrow">Catalogo FantaDrama</p><h3>Scegli le tue carte <span>{library.length}</span></h3></div><p>Le carte create dalla community sono disponibili per tutti.</p></div><div className="drama-card-grid">{library.map(card => <DramaCard key={card.catalogCardId || card.slug} card={card} owned={isOwned(card)} isAdding={adding === (card.catalogCardId || card.slug)} onAction={() => addToDeck(card)} actionLabel="Aggiungi al mazzo" />)}</div></section></div>
}
