import React, { useEffect, useState } from 'react'
import api from '../services/api'
import { Link } from 'react-router-dom'

const eventMood = (phase?: string) => phase === 'LIVE' ? { label: 'LIVE', className: 'event-live', icon: '⚡' } : phase === 'CONCLUSO' ? { label: 'Concluso', className: 'event-tense', icon: '◉' } : { label: 'In arrivo', className: 'event-upcoming', icon: '✦' }
function EventCollection({ title, description, events }: { title: string; description: string; events: any[] }) { return <section className="event-collection"><div><p className="eyebrow">{title}</p><p className="event-section-copy">{description}</p></div><div className="collection-grid">{events.map(e => { const mood = eventMood(e.phase); return <div key={e.id} className={`game-card event-card ${mood.className}`}>{e.imageUrl && <img className="event-card-image" src={e.imageUrl} alt="" />}<span className="event-status"><i>{mood.icon}</i>{mood.label}</span><h3>{e.title}</h3><p>{e.description || 'Preparati: può succedere di tutto.'}</p>{e.liveUpdate && <p className="event-live-update">✦ {e.liveUpdate}</p>}<span className="event-wave" aria-hidden="true" /><Link to={`/events/${e.id}`}>{e.phase === 'CONCLUSO' ? 'Vedi risultati →' : 'Apri evento →'}</Link></div> })}</div>{!events.length && <div className="empty-state">Nessun evento in questa sezione.</div>}</section> }
export default function EventsList() {
  const [events, setEvents] = useState<any[]>([]); const [canCreate, setCanCreate] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([api.get('/events'), api.get('/groups')]).then(([ed, gd]) => { setEvents(ed.data.events || []); setCanCreate((gd.data.groups || []).length > 0) }).catch(() => setError('Non riesco a caricare gli eventi. Riprova tra poco.')).finally(() => setLoading(false)) }, [])
  const active = events.filter(e => e.phase !== 'CONCLUSO'); const ended = events.filter(e => e.phase === 'CONCLUSO')
  return <div><div className="page-heading"><div><p className="eyebrow">Il prossimo capitolo</p><h2>Eventi</h2></div>{canCreate && <Link to="/events/create" className="btn">+ Crea evento</Link>}</div><EventCollection title="In programma e live" description="Entra nelle serate, acquista carte e segui la classifica in tempo reale." events={active} /><EventCollection title="Archivio delle serate" description="Gli eventi conclusi restano consultabili: risultati, vincitore, carte e punteggi non vanno persi." events={ended} />{loading && <div className="empty-state">Carico gli eventi della tua crew…</div>}{error && <div className="empty-state" role="alert">{error}</div>}</div>
}
