import React, { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { CalendarDays, Crown, LogIn, Play, PlusCircle, Share2, Trash2 } from 'lucide-react'
import api from '../services/api'
import PredictionForm from '../components/PredictionForm'

function date(value?: string) { return value ? new Date(value).toLocaleString('it-IT', { dateStyle: 'medium', timeStyle: 'short' }) : '—' }
function timeLabel(target?: string) { const diff = new Date(target || '').getTime() - Date.now(); if (diff <= 0) return 'adesso'; const min = Math.ceil(diff / 60_000); return min < 60 ? `${min} min` : `${Math.floor(min / 60)} h ${min % 60} min` }

export default function EventDetail() {
  const { id } = useParams(); const navigate = useNavigate()
  const [event, setEvent] = useState<any>(null); const [leaderboard, setLeaderboard] = useState<any[]>([]); const [selectedParticipant, setSelectedParticipant] = useState<any>(null); const [notice, setNotice] = useState(''); const [joining, setJoining] = useState(false)
  const load = useCallback(async () => { if (!id) return; try { const [detail, ranking] = await Promise.all([api.get(`/events/${id}`), api.get(`/events/${id}/leaderboard`)]); setEvent(detail.data.event); setLeaderboard(ranking.data.leaderboard || []) } catch { setEvent(null) } }, [id])
  useEffect(() => { void load(); const timer = window.setInterval(() => { if (document.visibilityState === 'visible') void load() }, 20_000); return () => window.clearInterval(timer) }, [load])
  if (!event) return <div className="empty-state">Sto caricando la drama room…</div>
  const mode = event.acquisitionMode === 'DIRECT' ? 'Acquisto diretto' : 'Asta esclusiva'; const marketCloses = event.acquisitionMode === 'AUCTION' ? new Date(new Date(event.startsAt).getTime() - 3600000).toISOString() : event.endsAt
  const join = async () => { setJoining(true); try { await api.post(`/events/${event.id}/join`); await load() } catch { setNotice('Non riesco a entrare nell’evento.') } finally { setJoining(false) } }
  const share = async () => { const url = `${window.location.origin}/events/${event.id}`; const text = `Entra con me a “${event.title}” su FantaDrama.`; try { if (navigator.share) await navigator.share({ title: event.title, text, url }); else { await navigator.clipboard.writeText(url); setNotice('Link dell’evento copiato: puoi incollarlo su WhatsApp, Telegram o social.') } } catch { /* User cancelled the native share dialog. */ } }
  const remove = async () => { if (!window.confirm(`Eliminare “${event.title}” e tutte le sue aste, carte dedicate e risultati?`)) return; try { await api.delete(`/events/${event.id}`); navigate('/events') } catch { setNotice('Non riesco a eliminare l’evento.') } }
  const leader = leaderboard[0]
  return <div className="event-detail-page">
    <section className="event-hero-detail">{event.imageUrl && <img src={event.imageUrl} alt="" />}<div><p className="eyebrow">{event.phase === 'LIVE' ? 'LIVE ORA' : event.phase === 'CONCLUSO' ? 'EVENTO CONCLUSO' : 'IN ARRIVO'}</p><h2>{event.title}</h2><p>{event.description || 'La crew è pronta al prossimo colpo di scena.'}</p><div className="event-meta"><span><CalendarDays size={15} /> Inizio: {date(event.startsAt)}</span><span>Fine: {date(event.endsAt)}</span><span>{mode}</span></div>{event.phase === 'IN_ARRIVO' && <p className="event-live-update">Mercato chiude tra {timeLabel(marketCloses)}.</p>}{event.liveUpdate && <p className="event-live-update">✦ {event.liveUpdate}</p>}
      <div className="event-hero-actions">{event.canJoin && <button className="btn" onClick={() => void join()} disabled={joining}><LogIn size={16} />{joining ? 'Entro…' : 'Aderisci all’evento'}</button>}{event.isCurrentUserParticipant && <span className="event-joined">✓ Sei iscritto all’evento</span>}{event.isCurrentUserParticipant && event.phase !== 'CONCLUSO' && <a className="btn" href="#carte-giocate"><Play size={16} /> Gioca carte acquistate</a>}<button className="btn btn-ghost" onClick={() => void share()}><Share2 size={16} /> Condividi</button>{event.isCurrentUserParticipant && event.phase !== 'CONCLUSO' && <Link className="btn btn-ghost" to={`/cards/create?eventId=${event.id}`}><PlusCircle size={16} /> Crea carta dedicata</Link>}{event.canManage && <button className="btn btn-danger" onClick={() => void remove()}><Trash2 size={16} /> Elimina evento</button>}</div></div></section>
    <section className="event-results-panel"><div><p className="eyebrow">Risultati in tempo reale</p><h3>{event.phase === 'CONCLUSO' && leader ? <><Crown size={17} /> Vince {leader.username}</> : 'Classifica provvisoria'}</h3><p>{event.phase === 'CONCLUSO' ? 'Punteggi definitivi della serata.' : 'I punti cambiano appena la crew conferma una carta giocata.'}</p></div><ol>{leaderboard.map((item, index) => <li key={item.userId}><b>{index + 1}</b>{item.avatar ? <img src={item.avatar} alt="" /> : <i>{item.username.slice(0, 1)}</i>}<span>{item.username}</span><strong>{item.points} pt</strong></li>)}{!leaderboard.length && <li className="empty-ranking">Nessun punto assegnato ancora.</li>}</ol></section>
    <section className="event-crew-panel"><div><p className="eyebrow">La crew dell’evento</p><h3>Chi partecipa <span>{event.participants?.length || 0}</span></h3><p>Non tutti i membri del gruppo devono giocare: entra prima dell’inizio per partecipare.</p></div><div className="event-participants">{(event.participants || []).map((participant: any) => <button type="button" key={participant.userId} className={selectedParticipant?.userId === participant.userId ? 'is-selected' : ''} onClick={() => setSelectedParticipant(participant)}>{participant.avatar ? <img src={participant.avatar} alt="" /> : <i>{participant.username?.slice(0, 1)}</i>}<span><b>{participant.username}</b><small>{participant.crewRole} · {participant.cards?.length || 0} carte</small></span></button>)}</div>{selectedParticipant && <article className="participant-profile"><button type="button" className="participant-close" onClick={() => setSelectedParticipant(null)}>×</button><div className="participant-profile-head">{selectedParticipant.avatar ? <img src={selectedParticipant.avatar} alt="" /> : <i>{selectedParticipant.username?.slice(0, 1)}</i>}<div><p className="eyebrow">Profilo giocatore</p><h3>{selectedParticipant.username}</h3><span>{selectedParticipant.crewRole}{selectedParticipant.city ? ` · ${selectedParticipant.city}` : ''}</span></div></div>{selectedParticipant.bio && <p>{selectedParticipant.bio}</p>}<div className="participant-cards"><strong>Carte valide per questo evento</strong>{selectedParticipant.cards?.length ? selectedParticipant.cards.map((card: any) => <article key={card.id}>{card.imageUrl && <img src={card.imageUrl} alt="" />}<span><b>{card.title}</b><small>{card.rarity} · {card.state}</small></span></article>) : <p>Nessuna carta acquistata per ora.</p>}</div></article>}</section>
    {event.isCurrentUserParticipant ? <PredictionForm eventId={event.id} phase={event.phase} acquisitionMode={event.acquisitionMode} closesAt={marketCloses} onSaved={() => void load()} /> : <section className="empty-state">Entra nell’evento per vedere il mercato, acquistare carte e confermare ciò che accade.</section>}{notice && <p className="profile-error">{notice}</p>}
  </div>
}
