import React, { useCallback, useEffect, useRef, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { CalendarDays, CreditCard, Pencil, PlusCircle, Send, ShoppingBag, Users } from 'lucide-react'
import api from '../services/api'
import ImageForge from '../components/ImageForge'

const formatDate = (value?: string) => value ? new Date(value).toLocaleString('it-IT', { dateStyle: 'medium', timeStyle: 'short' }) : 'Data da definire'
function Avatar({ person }: { person: any }) { return person.avatar ? <img src={person.avatar} alt="" /> : <i>{person.username?.slice(0, 1)}</i> }

export default function GroupDetail() {
  const { groupId } = useParams(); const [group, setGroup] = useState<any>(null); const [events, setEvents] = useState<any[]>([]); const [messages, setMessages] = useState<any[]>([]); const [draft, setDraft] = useState(''); const [notice, setNotice] = useState(''); const [selectedMember, setSelectedMember] = useState<any>(null); const [editing, setEditing] = useState(false); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [imageUrl, setImageUrl] = useState(''); const loadingRef = useRef(false)
  const load = useCallback(async () => { if (!groupId || loadingRef.current) return; loadingRef.current = true; try { const [gd, ed, md] = await Promise.all([api.get(`/groups/${groupId}`), api.get(`/events?groupId=${groupId}`), api.get(`/groups/${groupId}/messages`)]); setGroup(gd.data.group); setEvents(ed.data.events || []); setMessages(md.data.messages || []); if (!editing) { setName(gd.data.group.name || ''); setDescription(gd.data.group.description || ''); setImageUrl(gd.data.group.imageUrl || '') } } catch { setNotice('Non riesco ad aprire questa stanza privata.') } finally { loadingRef.current = false } }, [groupId, editing])
  useEffect(() => { void load(); const timer = window.setInterval(() => { if (document.visibilityState === 'visible') { void load() } }, 60_000); return () => window.clearInterval(timer) }, [load])
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!groupId || !draft.trim()) return; try { const r = await api.post(`/groups/${groupId}/messages`, { message: draft }); setMessages(all => [...all, r.data.message]); setDraft('') } catch { setNotice('Non riesco a inviare il messaggio.') } }
  const openMember = async (memberId: string) => { try { const r = await api.get(`/groups/${groupId}/members/${memberId}`); setSelectedMember(r.data.member) } catch { setNotice('Non riesco a caricare il profilo del partecipante.') } }
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { await api.put(`/groups/${groupId}`, { name, description, ...(imageUrl ? { imageUrl } : {}) }); setEditing(false); await load() } catch { setNotice('Non riesco a salvare le modifiche.') } }
  if (!group) return <div className="empty-state">Sto aprendo la stanza della crew…</div>
  return <div className="group-detail-page">
    <section className="group-detail-hero">{group.imageUrl && <img className="group-hero-image" src={group.imageUrl} alt="" />}<p className="eyebrow">Stanza privata</p><h2>{group.name}</h2><p>{group.description || 'Qui si decide chi legge meglio il caos.'}</p><div><span>Codice invito: <b>{group.code}</b></span><span><Users size={15} /> {group.members?.length || 0} membri</span>{group.currentUserRole === 'ADMIN' && <button className="btn btn-ghost" onClick={() => setEditing(!editing)}><Pencil size={15} /> Modifica crew</button>}</div></section>
    {editing && <form className="group-edit-panel" onSubmit={save}><p className="eyebrow">Gestione amministratore</p><h3>Nome, immagine e descrizione</h3><label>Nome gruppo<input className="input" value={name} onChange={e => setName(e.target.value)} /></label><label>Descrizione<textarea className="input profile-textarea" value={description} onChange={e => setDescription(e.target.value)} /></label><ImageForge kind="EVENT" imageUrl={imageUrl} onChange={url => setImageUrl(url)} /><div><button className="btn">Salva modifiche</button><button type="button" className="btn btn-ghost" onClick={() => setEditing(false)}>Annulla</button></div></form>}
    <section className="group-detail-grid"><div className="group-events-panel"><div className="group-panel-head"><div><p className="eyebrow">Eventi della crew</p><h3>Compra e gioca le carte</h3></div><div className="group-action-links"><Link to="/cards/create" className="btn btn-ghost"><PlusCircle size={15} /> Carta globale</Link><Link to={`/groups/${group.id}/cards`} className="btn btn-ghost"><CreditCard size={15} /> Carte</Link><Link to={`/events/create?groupId=${group.id}`} className="btn">+ Crea evento</Link></div></div><p className="group-auction-note">Apri una serata per entrare, vedere il mercato e controllare risultati e carte anche dopo la fine.</p>{events.length ? <div className="group-events-list">{events.map(item => <article key={item.id}><Link className="event-row-main" to={`/events/${item.id}`}><span className="event-date"><CalendarDays size={15} /> {item.phase === 'CONCLUSO' ? 'Evento concluso' : `Inizio ${formatDate(item.startsAt)}`}</span><h4>{item.title}</h4><p>{item.description || 'Un nuovo capitolo è pronto.'}</p><small>Fine: {formatDate(item.endsAt)} · {item.acquisitionMode === 'DIRECT' ? 'Acquisto diretto' : 'Asta esclusiva'}</small></Link><Link to={`/events/${item.id}`} className="btn"><ShoppingBag size={15} /> {item.phase === 'CONCLUSO' ? 'Risultati' : 'Apri evento'}</Link></article>)}</div> : <div className="empty-state">Non ci sono ancora eventi. Crea il primo capitolo della crew.</div>}</div>
      <aside className="group-members-panel"><p className="eyebrow">Partecipanti</p><h3>La tua crew</h3><p className="member-hint">Tocca un partecipante per vedere profilo e carte acquistate.</p>{(group.members || []).map((member: any) => <button type="button" key={member.id} onClick={() => void openMember(member.id)}><Avatar person={member} /><div><b>{member.username}</b><span>{member.crewRole}{member.city ? ` · ${member.city}` : ''}</span></div><small>Apri</small></button>)}</aside></section>
    {selectedMember && <section className="group-member-profile"><button type="button" className="participant-close" onClick={() => setSelectedMember(null)}>×</button><div className="participant-profile-head"><Avatar person={selectedMember} /><div><p className="eyebrow">Profilo partecipante</p><h3>{selectedMember.username}</h3><span>{selectedMember.crewRole}</span></div></div>{selectedMember.bio && <p>{selectedMember.bio}</p>}<div className="participant-cards"><strong>Carte acquistate / offerte in testa</strong>{selectedMember.cards?.length ? selectedMember.cards.map((card: any) => <Link key={card.id} to={card.eventId ? `/events/${card.eventId}` : `/groups/${group.id}/cards`}>{card.imageUrl ? <img src={card.imageUrl} alt="" /> : <i>✦</i>}<span><b>{card.title}</b><small>{card.rarity} · {card.state} · {card.credits} crediti</small><em>{card.eventTitle}</em></span></Link>) : <p>Per ora non ha carte acquistate né offerte in testa.</p>}</div></section>}
    <section className="group-chat-panel"><div><p className="eyebrow">Chat privata</p><h3>Parla con la crew</h3><span>Solo i membri di {group.name} possono leggere e scrivere qui.</span></div><div className="group-chat-messages">{messages.length ? messages.map((message: any) => <article key={message.id}><Avatar person={message} /><div><b>{message.username}</b><p>{message.message}</p><small>{formatDate(message.createdAt)}</small></div></article>) : <p>Nessun messaggio ancora. Rompi il ghiaccio.</p>}</div><form onSubmit={send}><input className="input" value={draft} maxLength={700} onChange={e => setDraft(e.target.value)} placeholder="Scrivi alla crew…" /><button className="btn"><Send size={15} /> Invia</button></form>{notice && <p className="profile-error">{notice}</p>}</section>
  </div>
}
