import React, { useState } from 'react'
import api from '../services/api'

export default function AdminModeration({ cards, appeals, onChanged }: { cards: any[]; appeals: any[]; onChanged: () => void }) {
  const [working, setWorking] = useState(''); const [notice, setNotice] = useState('')
  const review = async (id: string, status: 'APPROVED' | 'REJECTED') => { setWorking(id); try { await api.post(`/admin/cards/${id}/review`, { status }); setNotice(status === 'APPROVED' ? 'Carta approvata: entrerà nelle aste dei nuovi eventi.' : 'Carta rifiutata.'); onChanged() } catch { setNotice('Non riesco a aggiornare la carta.') } finally { setWorking('') } }
  const decide = async (id: string, decision: 'CONFIRMED' | 'DENIED') => { const note = window.prompt('Motivazione della decisione (facoltativa):') || ''; setWorking(id); try { await api.post(`/admin/appeals/${id}/decision`, { decision, note }); setNotice('Ricorso deciso e utente avvisato.'); onChanged() } catch { setNotice('Non riesco a decidere il ricorso.') } finally { setWorking('') } }
  const pending = cards.filter((card) => card.status === 'PENDING')
  return <><section className="admin-panel admin-cards"><h3>Carte in attesa di approvazione</h3>{pending.length ? pending.map((card) => <article className="admin-row" key={card.id}>{card.imageUrl && <img className="admin-card-preview" src={card.imageUrl} alt="" />}<div><strong>{card.title}</strong><p>{card.creatorName || 'Giocatore'} · in attesa</p></div><button type="button" className="btn btn-ghost" disabled={working === card.id} onClick={() => void review(card.id, 'APPROVED')}>Approva</button><button type="button" className="admin-danger" disabled={working === card.id} onClick={() => void review(card.id, 'REJECTED')}>Rifiuta</button></article>) : <p className="muted">Nessuna carta in attesa.</p>}</section><section className="admin-panel"><h3>Ricorsi aperti</h3>{appeals.length ? appeals.map((appeal) => <article className="admin-row" key={appeal.id}><div><strong>Ricorso evento</strong><p>{appeal.message}</p></div><button type="button" className="btn btn-ghost" disabled={working === appeal.id} onClick={() => void decide(appeal.id, 'CONFIRMED')}>Conferma carta</button><button type="button" className="admin-danger" disabled={working === appeal.id} onClick={() => void decide(appeal.id, 'DENIED')}>Nega carta</button></article>) : <p className="muted">Nessun ricorso aperto.</p>}</section>{notice && <p className="admin-notice">{notice}</p>}</>
}
