import React, { useState } from 'react'
import { Fingerprint } from 'lucide-react'
import { startAuthentication, startRegistration } from '@simplewebauthn/browser'
import api, { setAuthToken } from '../services/api'
import { firebaseAuth } from '../services/firebase'
import { signInWithCustomToken } from 'firebase/auth'

export function RegisterPasskeyButton() { const [message, setMessage] = useState(''); const [working, setWorking] = useState(false); const register = async () => { setWorking(true); setMessage(''); try { const options = await api.post('/passkeys/register/options'); const response = await startRegistration({ optionsJSON: options.data.options }); await api.post('/passkeys/register/verify', { response, requestId: options.data.requestId }); setMessage('Passkey registrata su questo dispositivo.') } catch { setMessage('Non riesco a registrare la passkey su questo dispositivo.') } finally { setWorking(false) } }; return <div className="passkey-box"><button type="button" className="btn btn-ghost" onClick={() => void register()} disabled={working}><Fingerprint size={17} />{working ? 'Configurazione…' : 'Attiva impronta / passkey'}</button>{message && <small>{message}</small>}</div> }
export function LoginPasskeyButton({ onSuccess }: { onSuccess: () => void }) { const [message, setMessage] = useState(''); const [working, setWorking] = useState(false); const login = async () => { setWorking(true); setMessage(''); try { const options = await api.post('/passkeys/login/options'); const response = await startAuthentication({ optionsJSON: options.data.options }); const verified = await api.post('/passkeys/login/verify', { response, requestId: options.data.requestId }); const credential = await signInWithCustomToken(firebaseAuth, verified.data.customToken); const token = await credential.user.getIdToken(true); localStorage.setItem('fd_token', token); setAuthToken(token); onSuccess() } catch { setMessage('Passkey non disponibile o non riconosciuta.') } finally { setWorking(false) } }; return <div className="passkey-box"><button type="button" className="btn btn-ghost" onClick={() => void login()} disabled={working}><Fingerprint size={17} />{working ? 'Verifica…' : 'Accedi con impronta / passkey'}</button>{message && <small>{message}</small>}</div> }
