import React, { useEffect, useState } from 'react'
import api from '../services/api'

type Props = { eventId: string; phase?: string; closesAt?: string; onSaved?: () => void }

function timeLeft(value?: string) {
  const seconds = Math.max(0, Math.ceil((new Date(value || '').getTime() - Date.now()) / 1000))
  if (!seconds) return 'chiusa'
  const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60)
  return hours ? `${hours}h ${minutes}m` : `${minutes} min`
}

export default function PredictionForm({ eventId, phase, onSaved }: Props) {
  const [auctions, setAuctions] = useState<any[]>([]); const [claims, setClaims] = useState<any[]>([]); const [wallet, setWallet] = useState<any>(null)
  const [amounts, setAmounts] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const [working, setWorking] = useState(''); const [currentUserId, setCurrentUserId] = useState('')
  const load = async () => { try { const [auctionData, claimData] = await Promise.all([api.get(`/auctions/event/${eventId}`), api.get(`/claims/event/${eventId}`)]); setAuctions(auctionData.data.auctions || []); setWallet(auctionData.data.wallet); setCurrentUserId(auctionData.data.currentUserId || ''); setClaims(claimData.data.claims || []) } catch { setMessage('Non riesco a caricare le aste in questo momento.') } }
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30_000); return () => window.clearInterval(timer) }, [eventId])
  const bid = async (auction: any) => { const amount = Number(amounts[auction.id]); setWorking(`bid-${auction.id}`); setMessage(''); try { await api.post(`/auctions/${auction.id}/bid`, { amount }); setMessage(`Offerta di ${amount} crediti registrata.`); await load(); onSaved?.() } catch (error: any) { const code = error.response?.data?.error; setMessage(code === 'insufficient_credits' ? 'Non hai abbastanza crediti disponibili per questa offerta.' : code === 'bid_too_low' ? `Devi offrire almeno ${(auction.leaderId ? auction.currentBid + auction.minIncrement : auction.openingBid)} crediti.` : code === 'auction_closed' ? 'L’asta è già chiusa.' : 'Non riesco a registrare il rilancio.') } finally { setWorking('') } }
  const claim = async (auction: any) => { const note = window.prompt(`Descrivi cosa è successo per “${auction.title}” (facoltativo):`) ?? ''; setWorking(`claim-${auction.id}`); try { await api.post(`/claims/event/${eventId}`, { auctionId: auction.id, note }); setMessage('Richiesta inviata: servono due conferme o due negazioni.'); await load() } catch (error: any) { setMessage(error.response?.data?.error === 'claim_not_available' ? 'Puoi dichiarare la carta solo durante l’evento.' : 'Non riesco a inviare la richiesta.') } finally { setWorking('') } }
  const vote = async (claim: any, decision: 'CONFIRM' | 'DENY') => { setWorking(`vote-${claim.id}`); try { await api.post(`/claims/${claim.id}/vote`, { vote: decision }); await load() } catch { setMessage('Non riesco a registrare il tuo voto.') } finally { setWorking('') } }
  const appeal = async (claim: any) => { const message = window.prompt('Scrivi il motivo del ricorso:'); if (!message) return; setWorking(`appeal-${claim.id}`); try { await api.post(`/claims/${claim.id}/appeal`, { message }); setMessage('Ricorso inviato all’amministratore.'); await load() } catch { setMessage('Non riesco ad aprire il ricorso.') } finally { setWorking('') } }
  const credits = Math.max(0, Number(wallet?.balance ?? 0) - Number(wallet?.reserved ?? 0))
  const live = phase === 'LIVE'
  return <section className="prediction-panel auction-panel"><div><p className="eyebrow">Mercato del caos</p><h3>Aste delle carte</h3><p><b>{credits}</b> crediti disponibili {wallet?.reserved ? `· ${wallet.reserved} in offerte` : ''}</p>{live && <p className="claim-help">Hai una carta vinta? Quando succede davvero, premi <b>Segnala carta avvenuta</b>: servono due conferme o la decisione dell’amministratore.</p>}</div>
    <div className="auction-grid">{auctions.map((auction) => { const minimum = auction.leaderId ? Number(auction.currentBid) + Number(auction.minIncrement) : Number(auction.openingBid); const owned = auction.status === 'WON' && auction.ownerId === currentUserId; return <article className={`auction-card ${auction.status !== 'OPEN' ? 'is-closed' : ''}`} key={auction.id}><img src={auction.imageUrl} alt="" /><div><small>{auction.rarity}</small><h4>{auction.title}</h4><p>{auction.description}</p><strong>{auction.currentBid ? `${auction.currentBid} crediti` : `Base ${auction.openingBid} crediti`}</strong><span>{auction.status === 'OPEN' ? `Chiude tra ${timeLeft(auction.closesAt)}` : auction.status === 'WON' ? `Vinta da ${auction.ownerName}` : 'Nessuna offerta'}</span>{auction.status === 'OPEN' && <div className="auction-bid"><input className="input" type="number" min={minimum} value={amounts[auction.id] ?? minimum} onChange={(event) => setAmounts((all) => ({ ...all, [auction.id]: event.target.value }))} /><button type="button" className="btn btn-ghost" disabled={working === `bid-${auction.id}`} onClick={() => void bid(auction)}>{working === `bid-${auction.id}` ? 'Invio…' : 'Rilancia'}</button></div>}{live && owned && <button type="button" className="btn btn-ghost claim-action" disabled={working === `claim-${auction.id}`} onClick={() => void claim(auction)}>Segnala carta avvenuta</button>}</div></article> })}</div>
    {claims.length > 0 && <div className="claim-board"><p className="eyebrow">Verifiche della crew</p>{claims.map((claim) => <article key={claim.id}><div><strong>{claim.cardTitle}</strong><span>{claim.claimantName} · {claim.status}</span>{claim.note && <p>{claim.note}</p>}<small>{claim.votes.filter((vote: any) => vote.vote === 'CONFIRM').length} conferme · {claim.votes.filter((vote: any) => vote.vote === 'DENY').length} negazioni</small></div>{claim.status === 'PENDING' && <div><button type="button" onClick={() => void vote(claim, 'CONFIRM')} disabled={working === `vote-${claim.id}`}>Conferma</button><button type="button" onClick={() => void vote(claim, 'DENY')} disabled={working === `vote-${claim.id}`}>Nega</button></div>}{['CONFIRMED', 'DENIED'].includes(claim.status) && <button type="button" onClick={() => void appeal(claim)} disabled={working === `appeal-${claim.id}`}>Ricorso</button>}</article>)}</div>}
    {message && <p className="prediction-message" role="status">{message}</p>}
  </section>
}
